### ISSUE TITLE
Kind request for more examples and demos

### ISSUE THREAD

**Issue by gwpl** [qdrant/rust-client#107]
Kind request for people considering to try qdrant with Rust programs.
Could you create more tutorials and examples that illustrate also how to use rust-client together e.g. with https://github.com/pepperoni21/ollama-rs generated embeddings, and other potential libraries/solutions?

**Comment by timvisee** [comment]
We have a lot of examples over on our documentation showing each available function: https://qdrant.tech/documentation/

We're currently doing a Rust client rewrite, which means that the interface might change in some time. The idea is to greatly improve it because it can be a bit cumbersome to use at this time. We'll probably provide more examples once that process is done.

**Comment by Anush008** [comment]
You can also refer to https://api.qdrant.tech for snippets of the improved SDK.
